server:
  servlet:
    context-path: /hs-access-facepay
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    resource_id: @server.hdp.resouce_id@
    delay: @server.hdp.delay@
    pool: @server.hdp.pool@
  constant:
    model: @server.constant.model@
    partner_id: @server.constant.partner_id@
    isv_id: @server.constant.isv_id@
    security: @server.constant.security@
  keys:
    999:
      private-key: @server.keys.999.private.key@
      public-key: @server.keys.999.public.key@
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true