server:
  servlet:
    context-path: /hs-access-facepay
  port: @server.port@
hdp:
  ip: @hdp.ip@
  port: @hdp.port@
  token: @hdp.token@
  resource-id: @hdp.resouce-id@
  delay: 5
  pool: 20

spring:
  datasource:
    enabled: @spring.datasource.druid.enabled@
    name: mysql
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: @spring.datasource.druid.url@
      username: @spring.datasource.druid.username@
      password: @spring.datasource.druid.password@
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

constant:
  seed: 2