server:
  servlet:
    context-path: /hs-access-facepay
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    resource-id: @server.hdp.resouce-id@
  partner:
    - partner-id: @server.partner.999.partner-id@
      isv:
        - isv-id: @server.partner.999.isv.isv-id@
          need-verify: false

spring:
  datasource:
    enabled: false
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true