server:
  servlet:
    context-path: /hs-access-facepay
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    resource-id: @server.hdp.resouce-id@
#    选配配置
#    delay: 5
#    pool: 25
  constant:
    model: @server.constant.model@
    partner-id: @server.constant.partner-id@
    isv-id: @server.constant.isv-id@
#    选配配置
#    security: cb1dc9980f164b08a12ac821494b89ed
#  convert:
#    bill: com.yuntai.upp.access.helper.BillHelper
#    present: com.yuntai.upp.access.helper.PresentHelper
  keys:
    10000-999:
      private-key: @server.keys.10000-999.private.key@
      public-key: @server.keys.10000-999.public.key@
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
debug: true