server:
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    hosid: @server.hdp.hosid@
    delay: @server.hdp.delay@
    pool: @server.hdp.pool@
  constant:
    partner: @server.constant.partner@
    path: @server.constant.path@
    file: @server.constant.file@
  access:
    model: @server.access.model@