server:
  port: @server.port@

hdp:
  ip: @hdp.ip@
  port: @hdp.port@
  token: @hdp.token@
  hosid: @hdp.hosid@
  delay: @hdp.delay@
  pool: @hdp.pool@

constant:
  partner: @constant.partner@
  path: @constant.path@
  file: @constant.file@