#############################
#	注释掉的配置均为可选择配置	#
#############################
server:
  servlet:
    context-path: /hs-access-facepay
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    resource-id: @server.hdp.resouce-id@
  constant:
    model: @server.constant.model@
    partner-id: @server.constant.partner-id@
    isv-id: @server.constant.isv-id@
  partners:
    - partner-id: @server.constant.partner-id@
      isvs:
      - isv-id: @server.constant.isv-id@
        key:
          private-key: @server.keys.10000-999.private.key@
          public-key: @server.keys.10000-999.public.key@

spring:
  datasource:
    enabled: false
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true