server:
  port: @server.port@
  hdp:
    ip: @server.hdp.ip@
    port: @server.hdp.port@
    token: @server.hdp.token@
    hosid: @server.hdp.hosid@
    delay: @server.hdp.delay@
    pool: @server.hdp.pool@
  constant:
    model: @server.constant.model@
    partner: @server.constant.partner@
